name: Release Binaries

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: darwin

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Build binary
      run: |
        GOOS=${{ matrix.platform }} GOARCH=amd64 go build -o age .

    - name: Zip the binary
      run: zip age-${{ matrix.platform }}-${{ github.sha }}.zip age

    - name: Upload Artifact to Existing Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./age-${{ matrix.platform }}-${{ github.ref_name }}.zip
        asset_name: age-${{ matrix.platform }}-${{ github.ref_name }}.zip
        asset_content_type: application/zip
